# Etapa de resolucion de dependencias
FROM maven:3.9-eclipse-temurin-17 as build
WORKDIR /app
COPY pom.xml .
# Intentar cachear dependencias instalando offline
RUN mvn dependency:go-offline -B
COPY src src
RUN mvn clean package -DskipTests

# Etapa de despliegue
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
