# Etapa de resolucion de dependencias
FROM eclipse-temurin:17-jdk-alpine as deps
WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B

# Etapa de construccion
FROM eclipse-temurin:17-jdk-alpine as build
WORKDIR /app
COPY --from=deps /app/ .
COPY src src
RUN ./mvnw clean package -DskipTests

# Etapa de despliegue
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
